"""Mock summarizer — deterministic, offline, zero-cost.

Used when DRY_RUN is on or no summarizer key is set, so the whole pipeline and
site render end-to-end before wiring a paid model. Output is clearly marked as a
placeholder (provider='mock') so the site/DB can flag it and never mistake it
for a real summary.
"""
from __future__ import annotations

import re
from typing import Optional

from .base import Summary
from .verify import Verdict


def _first_sentences(text: str, n: int = 2) -> str:
    text = re.sub(r"\s+", " ", (text or "").strip())
    if not text:
        return ""
    parts = re.split(r"(?<=[.!?])\s+", text)
    return " ".join(parts[:n]).strip()


class MockSummarizer:
    name = "mock"
    model = "mock-1"

    def summarize(self, *, title: str, venue: Optional[str], text: str) -> Summary:
        from ..topics import tag_for_text

        lead = _first_sentences(text, 2) or f"This paper, '{title}', concerns a bioinformatics topic."
        return Summary(
            provider=self.name,
            model=self.model,
            topic=tag_for_text(f"{title} {text[:2000]}")[0],
            difficulty="intermediate",
            tldr=f"[placeholder] {_first_sentences(text, 1) or title}",
            problem=f"[placeholder] The paper addresses the question introduced as: {lead}",
            methods="[placeholder] Methods summary will be generated by the real model (Gemini) once a key is configured.",
            findings="[placeholder] Key findings will be generated by the real model.",
            why="[placeholder] Significance will be generated by the real model.",
            limitations="[placeholder] Limitations will be generated by the real model.",
            takeaway=f"[placeholder] Takeaway for '{title[:60]}' pending real summarization.",
        )


class MockVerifier:
    """Offline verifier — always passes so the pipeline flows without a key.
    Clearly marked (provider='mock') so nothing is mistaken for real checking."""

    name = "mock"
    model = "mock-1"

    def verify(self, *, title: str, source_text: str, summary: Summary) -> Verdict:
        return Verdict(
            verdict="pass",
            score=0.9,
            confidence=0.9,
            unsupported_claims=[],
            notes="[mock] not really verified — real check runs once an Anthropic key is set.",
            provider=self.name,
            model=self.model,
        )
